### ISSUE TITLE
BrowserSync

### ISSUE THREAD

**Issue by jeffscottward** [shanewilson/react-webpack-example#14]
Ability to scroll, use keyboard commands, across all browsers is crazy awesome.

**Comment by shanewilson** [comment]
I had an older version working with browsersync. I didn't really like how it worked with webpack though, the two of them together seemed to be worse than either on their own.

https://github.com/shanewilson/react-webpack-example/tree/d7d251bea5935ceafdd89700ad6ff986c32c506c

could look into it again though

**Comment by jeffscottward** [comment]
any progress on this?

**Comment by shanewilson** [comment]
I can't figure out how to make it play nice with hot reloading.

**Comment by jeffscottward** [comment]
just updated to your latest, will try something out when I can.
