### ISSUE TITLE
Updating CSS vars doesn't change the output unless you rebuild

### ISSUE THREAD

**Issue by jeffscottward** [shanewilson/react-webpack-example#23]
PostCSS doesn't appear to hold css variables in memory w/ webpack?
Changing normal rules works just fine but the variable assignment seems hardcoded until you restart the app again.

try live-modifing any vars in _variables.css. Doesn't change anything.

**Comment by shanewilson** [comment]
Yes Webpack doesn't handle those vars at all really so I had to use: 
https://github.com/aaronj1335/webpack-postcss-tools

But the values have to be set at compile time:
https://github.com/aaronj1335/rework-webpack-loader#why-not-just-chain-plugins-together

> rework-webpack-loader solves this by going through all of the css files up front and creating a mapping from variable names to values, and then using this to resolve variables during compilation. the downside is that if you change variable values, you need to restart the webpack dev server, but the upside is that it handles css variables' cyclic dependencies.

**Comment by jeffscottward** [comment]
Understood. :+1:
